### PR TITLE
Add GitHub Actions

### PR DESCRIPTION
**Pull request by szabgab**
Currently the build fails because of #291 Once that is fixed I can update the PR and also add more versions of Perl.

Is this module supposed to work on Windows and macOS as well? If yes, I can add those as well to the CI

### CODE REVIEW

**Comment by jeffreykegler** [comment]
Yes, this module has tested Ok on cygwin, mswin32 and darwin, and I expect the upcoming release will do so. Note that keeping compatibility on these systems is a fairly desperate venture as I do not have direct access to a Windows box or a Mac.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by szabgab** [comment]
I've update the PR with several different versions of Perl in Docker containers and with Perl in Windows and macOS as well.

**Comment by jeffreykegler** [comment]
Rather than apply this PR here, I am going to move Marpa::R2 development into a Github organization account, and apply it there.  This may take a while, while I work on getting out the various releases I have underway.

**Comment by jeffreykegler** [comment]
I am closing this PR for the time being.  I will reopen it once this repo has been transfered.

**Comment by szabgab** [comment]
I am not sure why do you think it is preferable to merge this only after you move. At this end GitHub Action is just a few yaml files. They will be moved together with the repo when you move it and in the meantime they would already catch issues like the the missing test-file case. I'd be happy to hear your reason and learn from it.

**Pull request closed without merging**
