### PR TITLE
Repeatitive recognizer with same settings performance boost 

### PR DESCRIPTION
**Pull request by jddurand**

### CODE REVIEW

**Comment by jeffreykegler** [comment]
You may have seen my priority list on the IRC channel.  It may take me a little while to look at this.

**Comment by jddurand** [comment]
Yep - saw it - no pb

**Comment by rns** [comment]
@jddurand -- I have a [test script](https://github.com/rns/MarpaX-Regex/blob/master/t/perlreftut.t) where a recce is created with the same settings over 150 times (via SLG [`parse()`](https://metacpan.org/pod/distribution/Marpa-R2/pod/Scanless/G.pod#parse) ) -- it's must be running faster with this patch?

**Comment by jddurand** [comment]
@rns - definitely
The biggest the number of recce creations, the biggest the gain. I invite you to benchmark w/o this patch.
I observed a severe boost with my MarpaX::Languages::M4 which is creating recces a lot of times.

**Comment by jddurand** [comment]
C.f. the BEGIN block in https://github.com/jddurand/MarpaX-Languages-M4/blob/master/lib/MarpaX/Languages/M4/Impl/Parser.pm to get a touch with it without affecting your Marpa installation.

**Comment by rns** [comment]
@jddurand -- great, thanks, will try it on one of the coming days -- the work gets in.

**Comment by rns** [comment]
@jddurand -- Well, I couldn't resist trying -- https://github.com/rns/MarpaX-Regex/commit/e8f1a4fd4c6052df7e6627825c976628d647782e -- but it doesn't make a difference -- apparently because I don't use semantic action closures/nulling semantics at all in that project. Or am I doing it wrong?

Just remembered another potential user:
> I have to perform many parses on the same string. It really drags performance down if I recreate the recognizer on a new string every time.
-- https://groups.google.com/d/msg/marpa-parser/cMwFM3b0eDI/WdKo62Kc4cIJ

**Comment by jddurand** [comment]
This is the point.
No gain if no semantic action resolving.
Boost as soon as you have actions.

This user on the G+ group probably hitted the performance penalty I wanted to address. I personnally observe a factor 2.

**Comment by jeffreykegler** [comment]
@jddurand -- In assessing how much work you want to put into this, please bear in mind that it may never be merged.  This particular Marpa::R2 logic has tricked me many times -- changes that look simple take forever and have side effects and consequences I miss.  That per-parse-argument/constructor was an example.

So I want to warn you that when I look this over, I may simply say that I just don't want to mess with it.

**Comment by jddurand** [comment]
Jeffrey. I understand the point.
This patch is a getter/setter independant of the logic creating the data it is transmitting, though.

**Comment by jeffreykegler** [comment]
@jddurand -- I will look at the patch and think it over carefully later.

**Comment by jddurand** [comment]
@rns even with no action I observe a gain. Source of the test is below. Some measurements are in other comments.
@jeffreykegler this is not to convince you. No pb for me if it never merges. I just want to give concrete numbers.

```
#!env perl
use strict;
use diagnostics;
use Marpa::R2;
use Benchmark qw/cmpthese/;

declareOptim();

my ($nbAction, $nbRecce) = @ARGV;
$nbAction //= 100;
$nbRecce //= 100;

map {eval "sub action$_ {}"} (1..$nbAction);
cmpthese(50, {
             "[actions=$nbAction/recces=$nbRecce]" => sub { doit($nbAction, $nbRecce, 0) },
             "[Optimized version]" => sub { doit($nbAction, $nbRecce, 1) }
            });
exit 0;

sub doit {
  my ($nbAction, $nbRecce, $withPatch) = @_;

  CORE::state $registrations;

  my $sourceG = ":start ::= test\n";
  $sourceG .= "test ::= 'dummy'\n";
  foreach (1..$nbAction) {
    $sourceG .= "test ::= '$_' action => main::action$_\n";
  }
  my $g = Marpa::R2::Scanless::G->new({source => \$sourceG});
  foreach (1..$nbRecce) {

    my $r = Marpa::R2::Scanless::R->new({grammar => $g});

    if ($withPatch) {
      if (defined($registrations)) {
        $r->registrations($registrations);
      }
    }
    $r->read(\'dummy');
    $r->value();
    if ($withPatch) {
      if (! defined($registrations)) {
        $registrations = $r->registrations();
      }
    }
  }
}

sub declareOptim {
  #
  # Marpa internal optimisation: we do not want the closures to be rechecked every time
  # we call $r->value(). This is a static information, although determined at run-time
  # the first time $r->value() is called on a recognizer.
  #
  no warnings 'redefine';

  sub Marpa::R2::Recognizer::registrations {
    my $recce = shift;
    if (@_) {
      my $hash = shift;
      if (! defined($hash) ||
          ref($hash) ne 'HASH' ||
          grep {! exists($hash->{$_})} qw/
                                           NULL_VALUES
                                           REGISTRATIONS
                                           CLOSURE_BY_SYMBOL_ID
                                           CLOSURE_BY_RULE_ID
                                           RESOLVE_PACKAGE
                                           RESOLVE_PACKAGE_SOURCE
                                           PER_PARSE_CONSTRUCTOR
                                         /) {
        Marpa::R2::exception(
                             "Attempt to reuse registrations failed:\n",
                             "  Registration data is not a hash containing all necessary keys:\n",
                             "  Got : " . ((ref($hash) eq 'HASH') ? join(', ', sort keys %{$hash}) : '') . "\n",
                             "  Want: CLOSURE_BY_RULE_ID, CLOSURE_BY_SYMBOL_ID, NULL_VALUES, PER_PARSE_CONSTRUCTOR, REGISTRATIONS, RESOLVE_PACKAGE, RESOLVE_PACKAGE_SOURCE\n"
                            );
      }
      $recce->[Marpa::R2::Internal::Recognizer::NULL_VALUES] = $hash->{NULL_VALUES};
      $recce->[Marpa::R2::Internal::Recognizer::REGISTRATIONS] = $hash->{REGISTRATIONS};
      $recce->[Marpa::R2::Internal::Recognizer::CLOSURE_BY_SYMBOL_ID] = $hash->{CLOSURE_BY_SYMBOL_ID};
      $recce->[Marpa::R2::Internal::Recognizer::CLOSURE_BY_RULE_ID] = $hash->{CLOSURE_BY_RULE_ID};
      $recce->[Marpa::R2::Internal::Recognizer::RESOLVE_PACKAGE] = $hash->{RESOLVE_PACKAGE};
      $recce->[Marpa::R2::Internal::Recognizer::RESOLVE_PACKAGE_SOURCE] = $hash->{RESOLVE_PACKAGE_SOURCE};
      $recce->[Marpa::R2::Internal::Recognizer::PER_PARSE_CONSTRUCTOR] = $hash->{PER_PARSE_CONSTRUCTOR};
    }
    return {
            NULL_VALUES => $recce->[Marpa::R2::Internal::Recognizer::NULL_VALUES],
            REGISTRATIONS => $recce->[Marpa::R2::Internal::Recognizer::REGISTRATIONS],
            CLOSURE_BY_SYMBOL_ID => $recce->[Marpa::R2::Internal::Recognizer::CLOSURE_BY_SYMBOL_ID],
            CLOSURE_BY_RULE_ID => $recce->[Marpa::R2::Internal::Recognizer::CLOSURE_BY_RULE_ID],
            RESOLVE_PACKAGE => $recce->[Marpa::R2::Internal::Recognizer::RESOLVE_PACKAGE],
            RESOLVE_PACKAGE_SOURCE => $recce->[Marpa::R2::Internal::Recognizer::RESOLVE_PACKAGE_SOURCE],
            PER_PARSE_CONSTRUCTOR => $recce->[Marpa::R2::Internal::Recognizer::PER_PARSE_CONSTRUCTOR]
           };
  } ## end sub registrations

  sub Marpa::R2::Scanless::R::registrations {
    my $slr = shift;
    my $thick_g1_recce =
      $slr->[Marpa::R2::Internal::Scanless::R::THICK_G1_RECCE];
    return $thick_g1_recce->registrations(@_);
  } ## end sub Marpa::R2::Scanless::R::registrations

}

```

**Comment by jddurand** [comment]
```
================================================================================
0 action 100 recces
================================================================================
                         Rate [actions=0/recces=100]    [Optimized version]
[actions=0/recces=100] 18.1/s                     --                   -31%
[Optimized version]    26.2/s                    45%                     --

================================================================================
10 actions 100 recces
================================================================================
                          Rate [actions=10/recces=100]     [Optimized version]
[actions=10/recces=100] 7.14/s                      --                    -59%
[Optimized version]     17.4/s                    143%                      --

================================================================================
100 actions 100 recces
================================================================================
                           Rate [actions=100/recces=100]     [Optimized version]
[actions=100/recces=100] 1.07/s                       --                    -75%
[Optimized version]      4.30/s                     303%                      --

================================================================================
10 actions 1000 recces
================================================================================
                         s/iter [actions=10/recces=1000]     [Optimized version]
[actions=10/recces=1000]   1.20                       --                    -72%
[Optimized version]       0.340                     254%                      --

================================================================================
1000 actions 10 recces
================================================================================
                         s/iter [actions=1000/recces=10]     [Optimized version]
[actions=1000/recces=10]   2.11                       --                    -35%
[Optimized version]        1.36                      55%                      --
```

**Comment by rns** [comment]
@jddurand -- I can see the same gain with that script -- I missed `$registrations` save/restore that's why I didn't see it myself. 

Perhaps that `$registrations` save/restore thing should go to the patch (in SLR's `new()` or `value()`) otherwise the doc needs to tell that the application will have to do it every time.

**Comment by rns** [comment]
I think I can do a test case https://gist.github.com/rns/1c08a7a76a4dc8654591

**Comment by jddurand** [comment]
@rns I patched SLR.pod to warn the developper that it is its entire reponsability to call this method and that it has to call it explicitely to benefit from it.
Its side-effect is to by-pass any per-parse argument to $r->value.

**Comment by rns** [comment]
@jddurand -- yep and that's what I was missing, but got to read the doc finally -- when nothing else worked, that is :).

**Comment by jddurand** [comment]
@rns done - damned I could not avoid (or did not know to) the remote merge commit

**Comment by rns** [comment]
@jddurand -- great, thanks!

**Comment by jeffreykegler** [comment]
Can I close this?  Marpa::R2 is stable, so this will never go into it.  If it's applicable to Marpa::R3, you could create a new pull request in that repo.

**Comment by jddurand** [comment]
Sure

**Pull request closed without merging**
